
[envs.windows]
command = "build\\windows_test_compiler.exe -i tests/{base}.rlx -o tests/build/{base}.exe --windows > NUL || tests\\build\\{base}.exe {args}"

[envs.linux]
command = "./build/linux_test_compiler.elf -i tests/{base}.rlx -o tests/build/{base}.elf --linux {args} > /dev/null && tests/build/{base}.elf {args}"