
[envs.windows]
command = "{RLX} -i tests/{base}.rlx -o tests/{base}.exe --windows > NUL || tests\\{base}.exe {args}"
env_vars = {RLX = "build\\windows_compiler.exe"}

[envs.linux]
command = "{RLX} -i tests/{base}.rlx -o tests/{base}.elf --linux > /dev/null && tests/{base}.elf {args}"
env_vars = {RLX = "build/linux_compiler.elf"}